server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:hopper.proxy.rlwy.net}:${DB_PORT:45811}/${DB_NAME:edutec_db}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=America/Santiago&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: America/Santiago

  flyway:
    enabled: true
    baseline-on-migrate: true
    default-schema: edutec_db
    schemas: edutec_db
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change-me-supersecret}
  expiration: ${JWT_EXPIRATION:86400000}  # 24h en milisegundos
